[package]
name = "omg_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
omg = { path = "../omg" }
omg_serde = { path = "../omg_serde" }
rocket = "0.5.0-rc.2"
